name: deploy github pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run: |
          npm install
          npm run build
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.ACTION_TOKEN }}
          API_TOKEN_GITHUB: ${{ secrets.ACTION_TOKEN }}
        with:
          source-directory: "dist/homepage"
          destination-github-username: "lfcamara.ti"
          destination-repository-name: "lfcamarati.github.io"
          user-email: lfcamara.ti@gmail.com
          target-branch: main
