name: deploy github pages
uses: tagus/git-deploy@v0.4.1
with:
  changes: public
  repository: git@github.com:lfcamarati/lfcamarati.github.io.git
  ssh_key: ${{ secrets.ACTION_TOKEN }}
  name: Lucas Câmara
  email: lfcamara.ti@gmail.com
  clean_repo: true
